name: fundacion_aip_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^13.2.1
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  provider: ^6.1.2
  signature: ^5.4.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/loaders/
    - assets/images/
    - .env
