export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_visita.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/Datos_lote2.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_lote1.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_lote3.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_lote4.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_lote5.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_aprendizaje.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_contacto_titular.dart';
export 'package:fundacion_aip_mobile/features/createFarm/presentation/widgets/datos_predio.dart';
